name: Format Python Code
on: push
jobs:
  python-code-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Display Python version
        run: python --version
      - name: Install packages
        run: pip install black autopep8 isort
      - name: Formatter
        run: |
          modified_files=$(git diff --name-only --diff-filter=ACMR ${{ github.event.before }} ${{ github.sha }})

          # Loop através dos arquivos modificados e aplicação de formatação
          for file in $modified_files; do
            black "$file"
            autopep8 --in-place --recursive --aggressive --aggressive "$file"
            isort "$file"
          done
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Format code automatically
          title: Fixes by format action
          body: This is an auto-generated PR with fixes.
          labels: automated pr
          branch: python-code-format-patches
