name: Format Python Code
on:
  push:
    branches:
      - main  # Altere para a branch principal do seu repositório

jobs:
  python-code-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"  # Altere para a versão do Python que você deseja usar
          architecture: "x64"

      - name: Display Python version
        run: python --version

      - name: Install packages
        run: pip install black autopep8 isort

      - name: Formatter
        run: |
          # Obtendo arquivos modificados
          modified_files=$(git diff --name-only --diff-filter=ACMR HEAD^ HEAD)

          # Loop através dos arquivos modificados e aplicação de formatação
          for file in $modified_files; do
            black "$file"
            autopep8 --in-place --recursive --aggressive --aggressive "$file"
            isort "$file"
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Format code automatically
          title: Fixes by format action
          body: This is an auto-generated PR with fixes.
          labels: automated pr
          branch: python-code-format-patches
